"""Increase password_hash length for PostgreSQL

Revision ID: 081ffdd056fc
Revises: 51c8559d9610
Create Date: 2025-07-06 13:57:46.169328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081ffdd056fc'
down_revision = '51c8559d9610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
