"""Add uploaded_by column to Question model for CSV uploads

Revision ID: 58d668d536b2
Revises: 081ffdd056fc
Create Date: 2025-07-07 10:51:36.685623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d668d536b2'
down_revision = '081ffdd056fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('uploaded_by')

    # ### end Alembic commands ###
